figure (1)
plot(t,e)
title('Error')
figure (2)
subplot(3,1,1)
plot(t,u_ff)
ylim([-5 5])
title('Feedforward Control Effort')
subplot(3,1,2)
plot(t,u_fb)
ylim([-5 5])
title('Feedback Control Effort')
subplot(3,1,3)
plot(t,u)
ylim([-10 10])
title('Total Control Effort')